### ISSUE TITLE
重複SDK問題

### ISSUE THREAD

**Issue by billxu0521** [huanyichuang/pms-taiwan-gateways#1]
這個真的是很棒的plugin 感謝開發

當WP系統存在另個使用ECPay的SDK會報錯
我的環境同時安裝ECPay Payment for WooCommerce
安裝pms-taiwan-gateways的話就會出現
`Fatal error: Cannot declare class ECPay_PaymentMethod, because the name is already in use in /home/txzgwcqk/public_html/test/wp-content/plugins/ecpay-payment-for-woocommerce/includes/ECPay.Payment.Integration.php on line 6`

若只存在一個ECPay SDK則可以使用

**Comment by billxu0521** [comment]
原因出自於ECPay Payment for WooCommerce中也使用同樣名稱的類別(使用ECPay的API)
還想不到兩全其美的解決方式

暫時先將兩個外掛都指向同一個SDK文檔使用

**Comment by huanyichuang** [comment]
感謝回報！之前的確是還沒有考慮到有 WooCommerce 的情況。
我有看到 Pull Request 了，我先來試試看使用 SendExtend 這個方法的話，在沒有 WooCommerce 的情況下是不是也可以正常運作。

**Comment by billxu0521** [comment]
主要是SDK的類別名重複(畢竟用同個檔案)
想到幾個解法都有點麻煩，我也剛碰WP的plug-in  

也許要多寫個判斷「如果ECpay for WooCommerce存在」去決定是否引入同個SDK這樣的做法
定期定額也有別的問題，我另開一個issue

**Comment by huanyichuang** [comment]
> 主要是SDK的類別名重複(畢竟用同個檔案) 想到幾個解法都有點麻煩，我也剛碰WP的plug-in
> 
> 也許要多寫個判斷「如果ECpay for WooCommerce存在」去決定是否引入同個SDK這樣的做法 定期定額也有別的問題，我另開一個issue

這樣感覺我可以直接暴力一點，把 Class 名稱重新定義就好 😂

**Comment by billxu0521** [comment]
這應該是最簡單直接的解法了:P

**Comment by huanyichuang** [comment]
這個我先列入 to-do，因為我前陣子看綠界的 SDK 其實有做了比較大的版本更新，我在想要不要直接引用新版的 SDK

**Comment by huanyichuang** [comment]
@billxu0521 因為新版 SDK 在實裝上還有問題 XD 所以我先暫時用原本的方法把它解掉。可以再試用看看。
