### ISSUE TITLE
自動約期授權(定期定額)的週期欄位問題

### ISSUE THREAD

**Issue by billxu0521** [huanyichuang/pms-taiwan-gateways#3]
pms有提供Day、Week、Month、Year
而ECpay只有Day、Month、Year

如果要介接就可能遇到週期屬性值落差(Week)的狀況
我想直接當使用ECpay的自動約期授權時禁止使用"Week"
但pms設定會員資格與付款方式是拆開來的，找不到比較適合的提示位置....

**Comment by huanyichuang** [comment]
> pms有提供Day、Week、Month、Year 而ECpay只有Day、Month、Year
> 
> 如果要介接就可能遇到週期屬性值落差(Week)的狀況 我想直接當使用ECpay的自動約期授權時禁止使用"Week" 但pms設定會員資格與付款方式是拆開來的，找不到比較適合的提示位置....

感謝回報唷，我來想想看可以怎麼解決。
另一個想法是，如果使用 Week 的話，就把綠界那邊傳的資料變成 Day = Week * 7 這樣

**Comment by billxu0521** [comment]
> 另一個想法是，如果使用 Week 的話，就把綠界那邊傳的資料變成 Day = Week * 7 這樣

這是個好方法！想到可能出現的缺點就是購買敘述跟付款敘述(綠界)不對等
「$100/週」 ->  「$100 每7天一次」

**Comment by huanyichuang** [comment]
@billxu0521 新版本已經把週的功能也加上去了唷～
